//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public float HourlyWage { get; set; }
        public float HoursWorked { get; set; }
        public bool Manager { get; set; }
        public float Gross_Earnings { get; set; }
        public float FWT { get; set; }
        public float Net_earnings { get; set; }
    }
}
